### ISSUE TITLE
Function App v2 referencing .NET Standard Lib (with ASP.NET Core packages): System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Server.Abstractions, Version=2.0.1.0

### ISSUE THREAD

**Issue by ChristianWeyer** [Azure/azure-functions-host#2364]
I have a very simple Function App v2 (with .NET Core 2.0).
This Function app references a .NET Standard lib (which in turn references some ASP.NET Core packages) and uses types from that lib.

When I start the Functions host locally & try to HTTP GET an address like http://localhost:7071/api/foo I get this exception:
```
[28/01/2018 19:49:35] A ScriptHost error has occurred
[28/01/2018 19:49:35] Exception while executing function: Function1. FunctionApp1: The type initializer for 'FunctionApp1.Function1' threw an exception. FunctionApp1: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Server.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Server.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

Those assemblies are all 'there' in the folder of the Function app.

There are some similar issues already posted, like:
https://github.com/Azure/Azure-Functions/issues/625
https://github.com/Azure/azure-functions-cli/issues/253
https://github.com/Azure/azure-functions-cli/issues/335

And a related SO post:
https://stackoverflow.com/questions/48039880/azure-functions-2-0-not-loading-referenced-libraries

However, none of them provide a solution or a viable work around.

Is there anything I am doing wrong here?
Thanks!

You can find a simple repro here:
https://github.com/ChristianWeyer/Functions-NetStandardLib_Repro

My setup:
-VS 2017 15.6.0 Preview 3.0
-Azure Functions and Web Jobs Tools: 15.0.40118.0

**Comment by fabiocav** [comment]
@ahmelsayed , the VS tools are still not pulling the latest runtime, correct? Do we have an ETA on when that is supposed to happen?

**Comment by ahmelsayed** [comment]
It should work now. Close all VS instances and you should be prompted for 1.0.8 on the next run.

**Comment by ahmelsayed** [comment]
for V2, if you have the latest update for the "Azure Functions and Web Jobs Tools" you should have the latest V2 cli which has this runtime version 

```
Azure Functions Core Tools (2.0.1-beta.22)
Function Runtime Version: 2.0.11415.0
```

make sure to go to Tools -> Extensions and Updates... then check the updates for that extension.

**Comment by ChristianWeyer** [comment]
I did already have the latest version of "Azure Functions and Web Job Tools".
Same errors still.

Thanks!

**Comment by ChristianWeyer** [comment]
Do you have any other insights @ahmelsayed ? Maybe you were able to try out the repro above?
Thanks!

**Comment by ChristianWeyer** [comment]
@fabiocav Any idea what could be the reason this scenario does not work (yet)? Thanks for any ideas.

**Comment by cschwendtner** [comment]
@ChristianWeyer - Could you please try to use the same version of `Microsoft.AspNetCore` and `Microsoft.AspNetCore.Mvc` (clean / rebuild after changing - just to be on the safe side)?

`<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.1" />`

**Comment by ChristianWeyer** [comment]
Hallo @cschwendtner - did that: same results here.
Thanks.

**Comment by cschwendtner** [comment]
Hi @ChristianWeyer - tried that with your sample and it works on my machine ;)

Just to be sure: I had to do a full clean / rebuild after changing.

**Comment by cschwendtner** [comment]
Hi @ChristianWeyer - I tried that with your sample and it works on my machine ;)

Just to be sure: I had to do a full clean / rebuild after changing.

**Comment by ChristianWeyer** [comment]
This is indeed strange. I did delete the bin folders and did a full rebuild.

![image](https://user-images.githubusercontent.com/888718/35866487-9e523132-0b57-11e8-8a01-b35bfd51d75d.png)

... after invoking a URL like http://localhost:7071/api/foo

(BTW: I am glad you didn't say 'it works on my Docker' ;-) )

**Comment by cschwendtner** [comment]
What I notice is that I am using a different Function runtime - I am using version 2.0.11415.0

The example used (for the screenshot) is not the same as in your sample repo, is it? I am just asking to make sure that I am using the right one.

(BTW: I am pretty sure it would - everything works on Docker ;) )

**Comment by ChristianWeyer** [comment]
Yeah, I am using a different branch of that sample. But I also tried the master branch. Same result.

Hm, not sure how I could get the runtime version you are using....
I have the latest VS Tools installed...
This is strange.

**Comment by ChristianWeyer** [comment]
Thanks for this hint @cschwendtner 
I had this version on my machine (although I have the latest Tools extension in VS!):

Azure Functions Core Tools (1.0.7)
Function Runtime Version: 1.0.11375.0

I did
npm install -g azure-functions-core-tools@core

and now I have this version:
Azure Functions Core Tools (2.0.1-beta.22)
Function Runtime Version: 2.0.11415.0

In VS I still get this:
![image](https://user-images.githubusercontent.com/888718/35871749-54f1d980-0b65-11e8-9946-dd2fa71c33ee.png)

... and the same errors.

**Comment by ChristianWeyer** [comment]
If I execute the sample from the command line, without VS - it works... something is very wrong here :-)

**Comment by cschwendtner** [comment]
Could you try to install the newest version of the extension manually? See [Azure Functions and Web Jobs Tools](https://marketplace.visualstudio.com/items?itemName=VisualStudioWebandAzureTools.AzureFunctionsandWebJobsTools)

**Comment by cschwendtner** [comment]
It seems that the Functions runtime (V2) that is used (by Visual Studio) is dependent on the extension - the extension seems to use the runtime that comes with it. See [this comment](https://github.com/Azure/Azure-Functions/issues/625#issuecomment-351563570), for a workaround see [this comment](https://github.com/Azure/Azure-Functions/issues/625#issuecomment-355453557). 
That would explain the behavior you observed (different version of the runtime used when started from Visual Studio).

**Comment by ChristianWeyer** [comment]
Oh my god - yes, [this](https://github.com/Azure/Azure-Functions/issues/625#issuecomment-351563570) did it. Thanks @cschwendtner !

Hopefully this will be fixed soon :-)
