### ISSUE TITLE
CosmosDb SQL Query results in "Unable to load DLL 'Microsoft.Azure.Documents.ServiceInterop.dll'"

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-host#2862]
Attempting to use the CosmosDB input binding in a C# Azure Function.  However when I run it to debug I see the following error.  You can see the function [code here](https://github.com/jeffhollan/functions-csharp-durable-store-stripe/blob/0b3b0db80a92d35ee9fee20c322649e2d8d6e927/ProcessOrder/DurableGenerateReport.cs#L35-L43)

Doing some searching looks like this can pop up related to .NET assembly loading stuff with native binaries, wondering if the latest v2 build from @fabiocav would resolve this or an issue with CosmosDb binding with SqlQuery

<img width="899" alt="cosmoserror" src="https://user-images.githubusercontent.com/7132626/40156483-941edc34-594e-11e8-80cf-988a95842b56.png">

EDIT: Also tried to do the query via the SDK directly and got same error. To confirm it's the native binary stuff or dependencies not getting included I also found [this stack overflow comment](https://stackoverflow.com/a/50164686/4778497)

**Comment by fabiocav** [comment]
This should be resolved on 2.0.11776. The VS tools have been updated (so has the version on NPM), this scenario has been validated. Can you confirm this works for you?

**Comment by codemillmatt** [comment]
I can confirm this error still exists in run time version 2.0.11857.0 (core tools version 2.0.1-beta.29)

I'm trying to do the same thing as @jeffhollan above - bind to Cosmos DB and also write a query w/ the SDK and I'm getting the same error.

**Code:**
```
public static async Task Run(
  [QueueTrigger("game-results", Connection = "AzureWebJobsStorage")]GameResult gameResult,
  [CosmosDB(databaseName: "games-db", collectionName: "games-coll", ConnectionStringSetting = "CosmosDBConnection")]
    DocumentClient client,
  TraceWriter log)
{
  Uri collectionUri = UriFactory.CreateDocumentCollectionUri("trashtalk-db", "trashtalk-coll");

  IDocumentQuery<FriendInfo> friendQuery = client.CreateDocumentQuery<FriendInfo>(collectionUri)
    .Where(fi => fi.FavoriteTeam == gameResult.Opponent)
    .AsDocumentQuery();

    while (friendQuery.HasMoreResults)
    {
      foreach (var friend in await friendQuery.ExecuteNextAsync<FriendInfo>())

     // and so on...
```
**Error:**
![capture](https://user-images.githubusercontent.com/2053639/41607857-a6756876-73ac-11e8-9fa5-7ee9db9ab222.PNG)

**Comment by codemillmatt** [comment]
My bad @fabiocav - screenshot was truncated & it was for the error with the `DocumentClient` as the input - not bound to a particular document.

To answer your questions:

* How I'm running:
  * Running locally on VS 2017 15.7.4. 
  * Compiled C# functions (v2.0). 
  * Core tools: 2.0.1-beta.29.  
  * Runtime: 2.0.11857.0
* The OS:
  * Win10 (10.0.17134)
* GitHub repo:
  * [This should do it](https://github.com/codemillmatt/functions-cosmos-repro)
  * 3 functions total **InsertDataFunction** populates the cosmos w/ some test data. **GetFriendFunction** shows exception w/ `DocumentClient`. **GetFriendBindingFunction** shows exception w/ binding.

Let me know if you want anything else - thanks!

**Comment by fabiocav** [comment]
Thank you!! Will get your repro setup and investigate.

One more thing... did you update your project to use beta.29? How are you running beta.29 from VS? Did you follow this instructions? https://github.com/Azure/azure-functions-vs-build-sdk/wiki/How-to-manually-update-the-Azure-Functions-Core-Tools

**Comment by codemillmatt** [comment]
Ugh!! That was it - I didn't have VS running beta.29! 🤦‍♂️ 

Thanks @fabiocav! Everything is working as it should be now!

**Comment by jeffhollan** [comment]
This is resolved now
