### ISSUE TITLE
Using ASP.NET Core 2.1.0-rc1-final with Functions 2.0.1-beta.28 -> "Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Server.Abstractions, Version=2.1.0.0 ..."

### ISSUE THREAD

**Issue by ChristianWeyer** [Azure/azure-functions-host#2901]
Hey all.

I have beta 28 installed:
```
Azure Functions Core Tools (2.0.1-beta.28)
Function Runtime Version: 2.0.11776.0

```
When executing a function referencing ASP.NET Core 2.1.0-rc1-final, I get this exception:

![2018-05-26_15-59-10](https://user-images.githubusercontent.com/888718/40576914-024f5768-60fe-11e8-92c3-99860f1e4f37.png)

```
[5/26/2018 3:00:05 PM] Executing 'Proxy' (Reason='This function was programmatically called via the host APIs.', Id=a2ca9110-8376-4319-8d1a-6991db5253af)
[5/26/2018 3:00:05 PM] Executed 'Proxy' (Failed, Id=a2ca9110-8376-4319-8d1a-6991db5253af)
[5/26/2018 3:00:05 PM] System.Private.CoreLib: Exception while executing function: Proxy. AspNetCoreProxyFunctionApp: The type initializer for 'AspNetCoreProxyFunctionApp.AspNetCoreProxy' threw an exception. AspNetCoreProxyFunctionApp: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Server.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file.
```

Please see this sample project to reproduce the issue:
https://github.com/ChristianWeyer/azure-functions-aspnetcore-proxy

**Comment by jbellmore** [comment]
I can confirm I am experience the same issue, trying to accomplish the same thing as @ChristianWeyer  with the same versions of runtimes/packages.

**Comment by ChristianWeyer** [comment]
Maybe @fabiocav has an opinion on this? ;-)

**Comment by jbellmore** [comment]
The most confusing part about these errors is that they are appearing in a pre-compiled application where all of the binaries are available in the same folder as the main .dll that contains the function being executed.

I even went so far as to publish the app using dotnet publish with the --self-contained param so even the runtime was included in the folder and that doesn't seem to work either.

Some information about how the function is being executed in the Azure function environment as well as what it is doing for assembly loading might help developers understand what can and can not be done in Azure functions for dotnet core.

It seems like Azure functions expects a specific version of the dll's and at this point the 2.1.0 bits are not available yet. Unfortunately requiring specific versions really limits the usefulness of Azure functions from a dotnet core perspective.

**Comment by fabiocav** [comment]
This has been addressed with the update we’re rolling out. If you create a function app in West US 2, you should be able to test with those new bits (2.0.11857). CLI will be available soon.

I can provide instructions on how to get the CLI bits working, but they’ll be rolling out early this week

**Comment by ChristianWeyer** [comment]
I still get this very same exception as above with the latest bits @fabiocav

**Comment by fabiocav** [comment]
Is that local? Or azure hosted? I'll run through your scenario again, but this had been validated. Is the repro you've linked to current?

**Comment by ChristianWeyer** [comment]
This is local.
And yep: the repo is current. Thanks!

**Comment by fabiocav** [comment]
I see the issue. It's an unfortunate side effect of how the ASP.NET Core builds up some of the dependencies (more specifically, the ApplicationPartManager implementation, that causes it to hit an issue with your scenario. This scenario is somewhat different, as it does run into a few mixed context loads. Good news is that I think there's an easy fix for this. I'll validate and keep you updated. We have another incremental release hitting soon, but I can make updated bits available earlier for testing.

**Comment by ChristianWeyer** [comment]
Thanks a ton for all your work @fabiocav !

**Comment by fabiocav** [comment]
Got a fix out for this. Validated that it works against your repro (although, there are other, unrelated issues with validation as the request is sent to the application from the proxy, but that seems to be an issue with the implementation)

**Comment by ChristianWeyer** [comment]
Ok, thanks. Any ETA for the fix to be used by us @fabiocav ? 😇

**Comment by fabiocav** [comment]
We're planning on another deployment early next week.

**Comment by ChristianWeyer** [comment]
If there is some way to test the fix earlier - I would be up for it (I have a talk prep pending and would need to check the fix, anyway).
Thanks @fabiocav

**Comment by fabiocav** [comment]
This is a bit raw, but you can use the artifacts from this build:
https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-script-y8o14/build/2.0.11886/job/0exdyn0sak341kea/artifacts

We'll likely have a CLI build today as well.

**Comment by ChristianWeyer** [comment]
This looks a crazy endeavour to get the raw artifacts working on my macOS... ;-P

**Comment by ChristianWeyer** [comment]
... a bit impatient 🤣 - as I wanted to demo that project in my conference talk next Monday.
Any chance to get a new core tools package for this fix (https://github.com/Azure/azure-functions-core-tools/releases)? @fabiocav

**Comment by fabiocav** [comment]
You can get the Core tools bits for this release here: https://ci.appveyor.com/project/appsvc/azure-functions-cli/build/2.0.1.372/artifacts

**Comment by ChristianWeyer** [comment]
Just tried it with that above package on macOS.
It works 👊🏻 (although it is executing the Web API request very slowly.... this was much faster the other day with earlier builds... hm)

Thanks a lot @fabiocav !

**Comment by ChristianWeyer** [comment]
It is *much* faster on Windows 😅

**Comment by fabiocav** [comment]
Closing this as resolved, but please let us know if you run into issues.
