### ISSUE TITLE
DI ITelemetryInitializer never executed 

### ISSUE THREAD

**Issue by riha** [Azure/azure-functions-host#4064]
#### Investigative information
- Function App version: 2.0
- Function Runtime Version: 2.0.12285.0
- Framework: .NET core 2.0
- Microsoft.ApplicationInsights package version: [2.9.0](https://www.nuget.org/packages/Microsoft.ApplicationInsights/2.9.0)

#### Repro steps
1. Clone [LogExtensionTest](https://github.com/riha/LogExtensionTest) test repo.
2. Add a `APPINSIGHTS_INSTRUMENTATIONKEY` key in local settings.
3. Run i local dev runtime and post any http payload against the endpoint.

#### Expected behavior
1. The `ReferrerTelemetryInitializer` dependency should be injected in the `Startup` class.
2. Once `log.LogInformation` are executed and an `TraceTelemetry` should be triggered and sent to AI. 
3. Once `HttpClient` `GetAsync` are executed and a `DependencyTelemetry` should be triggered and sent to AI.
4. The `Initialize` method in the `ReferrerTelemetryInitializer` class should intercept these and the code in that class should be executed. The end goal is to add a few properties to the Telemetry item being sent to AI

#### Actual behavior
1. The dependency in Startup **is** injected as long as one runs in .NET core 2.0, other wise not (not in 2.1 or 2.2)
2. The `Initialize` method is never executed ..?

#### Known workarounds
N/A 

#### Related information 
This has previously been discussed [here](https://stackoverflow.com/questions/54416463/custom-application-insight-telemetryinitializer-using-azure-function-v2) that @lmolkova replied to.

**Comment by fabiocav** [comment]
This is being resolved with a tooling update.

@brettsam can you link to the metadata change PR?

**Comment by brettsam** [comment]
This is because of #3731 -- The issue's been fixed (#4036)  and I'm working to get version 1.0.2 of the ExtensionsMetadataGenerator released to nuget soon.

**Comment by lmolkova** [comment]
I believe @riha concern was that on netstandard2.0, Configure IS invoked, but telemetry initializer is still not invoked. 
I was going to investigate it (and still going to), but snowmageddon keeps me behind on everything.

Can we keep it open? I'll try my best to have a look sometime this week.

**Comment by brettsam** [comment]
Oh, I misread that -- @riha do you have some sample code that shows what's not working? @lmolkova is right that the `ITelemetryInitializer.Intialize()` method should be called -- but currently only works in netcore2.0 projects (due to the tooling bug I mentioned above).

**Comment by lmolkova** [comment]
This is repro app: https://github.com/riha/LogExtensionTest

**Comment by brettsam** [comment]
@riha -- move your App Insights nuget reference back to 2.7.2 and it should work. When we run, that's what we're running against so the DI check for anything 2.9.0 won't be found. We'll be moving this forward soon so it won't be an issue (and we'll try to keep it on the latest) but for now we're still on 2.7.2.

**Comment by riha** [comment]
Thanks! Works like a charm and solves my issue.

**Comment by suppenburger** [comment]
How should one know with which App Insights version it works and with which version not. Could you please point me to the respective documentation?

**Comment by brettsam** [comment]
@suppenburger -- We're going to try to keep it in-step with the latest release as close as we can. We're now targeting 2.9.1, for example, so there's no requirement to hit 2.7.2 anymore. The most accurate way is to check what version of Microsoft.ApplicationInsights we use as a dependency here: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Logging.ApplicationInsights, but we don't have any real documentation (since it will likely change as versions move forward).

**Comment by DarinMacRae** [comment]
@brettsam Your last post was absolutely clutch. I finally got it working by going back to 2.9.1 (latest is 2.10) because of your hint. Many thanks.

**Comment by Riff451** [comment]
Hi, I don't know whether my issue is related to this one, but it looks so...
I'm trying to run the LogExtensionTest sample code that I forked [here](https://github.com/Riff451/LogExtensionTest) with a few changes:

- Target Framework: notcoreapp: 2.2
- Microsoft.ApplicationInsights: 2.10.0
- Microsoft.NET.Sdk.Functions: 1.0.29
- In the ITelemetryInitializer I'm setting a custom ITelemetry.Context.Operation.Id

And it works fine locally with this runtime: Function Runtime Version: 2.0.12555.0
Even though I needed to add an empty ApplicationInsights.config file to see the logs in AI.

The problem is when I deploy the code in an azure function app (runtime 2.0.12590.0): the custom ITelemetryInitializer is never called even if the Startup code is correctly executed and the implementation is registered into the ServiceCollection.

Thank you very much.

**Comment by brettsam** [comment]
Do you have app insights registered on the site? Check the APPINSIGHTS_INSTRUMENTATIONKEY app setting. Can you tell the startup code is actually running?

**Comment by Riff451** [comment]
@brettsam Thank you for your quick answer. It turned out that the problem was actually something different because the test code is fine. My bad. I didn't realise that before :) I'm having a different issue in my production project and that's why I was trying a simplified version based on the test code here. Unfortunately I still don't have enough information but it's definitely something wrong in my specific initializer code. Thanks again.
