### ISSUE TITLE
WEBSITE_CONTENTAZUREFILECONNECTIONSTRING as keyvault reference makes deployment slot swaps fail

### ISSUE THREAD

**Issue by nates321** [Azure/azure-functions-host#5306]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp: Thursday Nov 21 14:49:35 GMT -0800
- Function App version (1.0 or 2.0): 2
- Function App name: wllrr4he5a5ck-orch-funcapp
- Function name(s) (as appropriate): N/A
- Invocation ID: N/A
- Region: Central US

#### Repro steps

Provide the steps required to reproduce the problem:

1. Created  function app with WEBSITE_CONTENTAZUREFILECONNECTIONSTRING app setting set to a keyvault reference and a deployment slot named staging. 
2. published functions to the production slot
3. published functions to the staging slot
4. In the portal, try to swap the production and staging slot

#### Expected behavior

Provide a description of the expected behavior.

After trying to swap the slots, the swap should occur successfully, with the functions and non-slot settings in the staging slot being transferred to the production slot and the same the other way

#### Actual behavior

Provide a description of the actual behavior observed.

After step 4, an InternalServerError with no message appears. If I try to use autoswap or the CLI it also returns the same 500 error.

#### Known workarounds

Provide a description of any known workarounds.

Don't use a keyvault reference for this App Setting.

#### Related information 

Provide any related information 

Other app settings in my function app are keyvault references, but the swap works fine as long as WEBSITE_CONTENTAZUREFILECONNECTIONSTRING is not a keyvault reference. I found that this was the problem while talking to someone on the Azure Functions team.

**Comment by mhoeger** [comment]
Per James:
There is a known bug in this scenario, corresponding workitem is here:
(_Internal only_) Bug 6378863: FileShareManager.TryGetAzureFilesCredentials does not resolve KVAS connection string

Effects of this bug is that function apps using WEBSITE_CONTENTAZUREFILESCONNECTIONSTRING are unable to swap.

The guidance offered is to not configure WEBSITE_CONTENTAZUREFILECONNECTIONSTRING as a key vault reference to work around this bug. Potentially when they swap they can remove the key vault reference, swap, and then re-add the reference.

The earliest this fix can roll out is ANT88. However, this release currently has an unknown ETA

**Comment by chmarti** [comment]
Isn't WEBSITE_CONTENTAZUREFILECONNECTIONSTRING required consumption plans? So you're required to have WEBSITE_CONTENTAZUREFILECONNECTIONSTRING set or you see a warning about "Storage is not configured correctly", however if you set it then then you can't force different storage accounts for different slots (because they are swapped). If that is the case then isn't slot swapping is completely broken for Azure functions? Not sure how this scenario works in general even if you take keyvault references out of it.

**Comment by mattchenderson** [comment]
@mhoeger Supposedly this was resolved. Can you confirm and possibly close this out?

**Comment by ChrisProlls** [comment]
Not resolved on my side during deployment
````json
Deployment failed. Correlation ID: f171c78c-ad28-4426-aea4-cd9ae0bf57e9. {
  "Code": "BadRequest",
  "Message": "The parameter 'WEBSITE_CONTENTAZUREFILECONNECTIONSTRING' has an invalid value. Details: Cannot specify key vault references not referencing User Assigned Identity on Create Site.",
  "Target": null,
  "Details": [
    {
      "Message": "The parameter 'WEBSITE_CONTENTAZUREFILECONNECTIONSTRING' has an invalid value. Details: Cannot specify key vault references not referencing User Assigned Identity on Create Site."
    },
    {
      "Code": "BadRequest"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "01033",
        "MessageTemplate": "The parameter '{0}' has an invalid value. Details: {1}.",
        "Parameters": [
          "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
          "Cannot specify key vault references not referencing User Assigned Identity on Create Site"
        ],
        "Code": "BadRequest",
        "Message": "The parameter 'WEBSITE_CONTENTAZUREFILECONNECTIONSTRING' has an invalid value. Details: Cannot specify key vault references not referencing User Assigned Identity on Create Site."
      }
    }
  ],
  "Innererror": null
}
````

**Comment by onionhammer** [comment]
Issue is definitely not resolved. Any update on ETA for a fix?

This issue is presumably also related to Azure Pipelines deployment's `AzureFunctionsApp@1` task erroring with

"##[error]Error: Unable to find the storage account associated with the function app."

**Comment by jikuja** [comment]
https://github.com/Azure/Azure-Functions/issues/1195 mentioned in July that fix was in progress. Any progress or should we start writing workarounds for this issue?

**Comment by adityavaish** [comment]
Any progress here? Facing the same issue

**Comment by mhoeger** [comment]
Hi all - the fix is in for **failing slot swaps** because of WEBSITE_CONTENTAZUREFILECONNECTIONSTRING as a key vault reference. You should not be seeing this anymore and if your slot swap is failing for this reason, please provide details on this thread.

It sounds like the issue that other folks are facing is Function App **creation**. Is that correct? If so, please file your details in this issue: https://github.com/Azure/azure-functions-host/issues/7094
So far, it looks like DevOps and an ARM deployment have faced this issue.

Closing this issue for **failing slot swaps** as resolved.

**Comment by j2020v** [comment]
This is still an issue, swapping slots is failing 
I am deploying a consumption based plan function app, linux and is unable to perform a swap slot due to missing app settings below:

Error: BadRequest - Storage access failed. WEBSITE_CONTENTAZUREFILECONNECTIONSTRING or WEBSITE_CONTENTSHARE appsetting is missing (CODE: 400)
