### ISSUE TITLE
Azure Function ~3 does not support file upload >30 MB for node.js app exception "Microsoft.AspNetCore.Server.Kestrel.Core: Request body too large"

### ISSUE THREAD

**Issue by anilpras** [Azure/azure-functions-host#5548]
Please provide the following:

- Timestamp: 18:11 UTC 27th Jan 2020
- Function App version (1.0 or 2.0): ~3
- Function App name:  javauploadtest.azurewebsites.net
- Function name(s) (as appropriate): HttpTrigger2

#### Repro steps

Exception: System.Private.CoreLib: Exception while executing function: Functions.FileUpload. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'req'. Microsoft.AspNetCore.Server.Kestrel.Core: Request body too large.

The function app is configured with V3.

Here is how to reproduce
 
![image](https://user-images.githubusercontent.com/14159197/73201738-8a9a8d00-40ee-11ea-8993-13bbb3163ebf.png)

#### Known workarounds

Change the host version (host.json) and the function version to ~2 it enables the function to upload file up to 100 MB. 

Internal ICM: 169866859

**Comment by fabiocav** [comment]
@anilpras what hosting model were are you using when you see this (Windows/Linux, Consumption/Dedicated)?

**Comment by anilpras** [comment]
Windows, Consumption plan [Internal ICM: 169866859]

**Comment by fabiocav** [comment]
I believe @mhoeger has been followed up with you and you're currently unblocked, but my question was based on the exception message you've posted above. I'm assuming you're sharing what you're seeing locally, correct? I wouldn't expect the message above in the Windows hosted environment (where Kestrel is not in the picture).

**Comment by anilpras** [comment]
@fabiocav : server side it does log below:

Microsoft.AspNetCore.Server.IIS.BadHttpRequestException : Request body too large.
   at Microsoft.AspNetCore.Server.IIS.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.InitializeRequestIO()
   at async Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1

**Comment by jcoolsen** [comment]
> I believe @mhoeger has been followed up with you and you're currently unblocked

I'm having this issue as well. Are there any work-arounds that you can share? I have tried everything that I can think of, short of redesigning the application.
The attributes `DisableRequestSizeLimit` and `RequestSizeLimit` do not make any difference, nor does assigning to `req.HttpContext.Features.Get<Microsoft.AspNetCore.Http.Features.IHttpMaxRequestBodySizeFeature>().MaxRequestBodySize`. Any pointers?

**Comment by mhoeger** [comment]
This issue does not reproduce with just our code so I'm trying to investigate what else has changed. Thanks for your patience! 

Only known workaround for now is to run on V2.

**Comment by jcoolsen** [comment]
@mhoeger, thank you for your response. I'm not entirely sure that I understand that first sentence. Do you need anything more from us in order to be able to reproduce the issue?

Thanks for the suggestion on v2, probably easier than rearchitecting the solution.

**Comment by mhoeger** [comment]
@jcoolsen - i'm able to reproduce the issue, thank you :) Also worth noting that this issue does not reproduce in Linux Consumption (because the issue is related to IIS)

**Comment by fabiocav** [comment]
Fixed with #5820

**Comment by dalibor-sanzeru** [comment]
Hi,
I have the same problem with following setup:

- VS2019 - local functions debug, 
- Windows 10,
- Microsoft.NET.Sdk.Functions 3.0.6
- Azure Functions Core Tools (3.0.2245 Commit hash: 1d094e2f3ef79b9a478a1621ea7ec3f93ac1910d)
- Function Runtime Version: 3.0.13139.0
- TargetFramework: netcoreapp3.1 
- AzureFunctionsVersion: v3

File upload size 42MB over HttpTrigger.

Was this fix shipped yet so this bug is fixed?  Which nuget, sdk?

Thanks. for advice & help.

Dalibor.

**Comment by jcoolsen** [comment]
@dalibor-sanzeru , I have never seen the problem in local debug, but is is not yet resolved in Azure Functions as far as I can determine. I don't know when to expect it to go live.
