### ISSUE TITLE
[Custom Handlers]Forward HttpTrigger request when enableForwardingHttpRequest=true

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#6305]
The handler is always invoked with the function's name as the path.

Looks like the problem is here:
https://github.com/Azure/azure-functions-host/blob/242d08327b9cb751d7f9ccae1fb8d4570c8b0286/src/WebJobs.Script/Workers/Http/DefaultHttpWorkerService.cs#L175

`httpRequestMessage` is always empty because:
https://github.com/Azure/azure-functions-host/blob/242d08327b9cb751d7f9ccae1fb8d4570c8b0286/src/WebJobs.Script/Workers/Http/DefaultHttpWorkerService.cs#L161-L162

**Comment by pragnagopa** [comment]
This is recent regression in commit # https://github.com/Azure/azure-functions-host/commit/dcdd1c251fb041d6828d7b2cdcad99a311518cbe when we moved away from `HttpRequestMessageFeature`

This issue also does not populate Http Request content. For example, if HttpTrigger is a `POST` with json body, CustomHandler would be missing Body as well.

Assigning to @yojagad for further investigation.

@yojagad  - We need to build HttpRequestMessage from original HttpTrigger request. Can you please take a look?

**Comment by anthonychu** [comment]
@pragnagopa @yojagad I was trying to test it out to write up the docs. I ended up hacking together a fix so I could continue testing. If it's close to a good solution, maybe we can iterate on it and get it merged for this sprint? I just pushed it here: https://github.com/anthonychu/azure-webjobs-sdk-script/compare/242d08327b9cb751d7f9ccae1fb8d4570c8b0286...anthonychu:20200705-fix-customhandler-path

**Comment by pragnagopa** [comment]
Thanks @anthonychu . Unfortunately, path is just one of the issues. Forwarding http request is still broken.  

@yojagad - we should try to get the fix in for this sprint. Reassigning. If there are not good alternative to `HttpRequestMessageFeature`, for the short term revert to previous commit?

**Comment by pragnagopa** [comment]
Reassigning to current sprint as this is a regression and will block docs/samples updates for CustomHandlers.

**Comment by anthonychu** [comment]
Great. Thanks!

Do you know if this regression is in the host release that's scheduled to start rolling out this week? (3.0.13904?)

**Comment by pragnagopa** [comment]
It is part of the next release: v3.0.14063  which will be rolling out soon. I will update release annoucement to pin users to previous release

**Comment by anthonychu** [comment]
Is custom handlers using httpWorker affected (aside from that event hubs issue)? If not, we probably don't need to recommend pinning for the customWorker section as that's not documented yet. We'll just wait until these fixes roll out before documenting.

**Comment by pragnagopa** [comment]
> Is custom handlers using httpWorker affected (aside from that event hubs issue)

Yes, :(  - `customHandler` vs `httpWorker` is only in the config. Once config is populated, it is the same code. I updated release announcement page with breaking changes. 

cc @FinVamp1  - in case any CRIs will be filed.

**Comment by anthonychu** [comment]
Thanks @pragnagopa. And pinning only works on Windows, right?

**Comment by pragnagopa** [comment]
Pinning works on windows (all skus) and linux dedicated.

**Comment by anthonychu** [comment]
OK. So if someone is on Linux consumption, they will be broken unless they switch to dedicated or Windows.

**Comment by pragnagopa** [comment]
> on Linux consumption, they will be broken unless they switch to dedicated or Windows.

That is correct. 

cc @fabiocav  for visibility. 

Since the feature is in preview, does not meet the bar for hotfix.  We will be preparing for next release this week and fix will be part of it.
