### ISSUE TITLE
[CustomHandler]Azure golang function does not receive request payload in the body

### ISSUE THREAD

**Issue by mpurusottamc** [Azure/azure-functions-host#6444]
I have created an Azure Function in Go. The function is working properly in local machine with GET & POST requests. When published, request payload sent via POST is not available in the request object. Here's my code:

```
# Main function
mux := http.NewServeMux()
mux.HandleFunc("/hello", helloWorld)
logrus.Fatal(http.ListenAndServe(":"+httpInvokerPort, mux))

# helloWorld function
func helloWorld(w http.ResponseWriter, r *http.Request) {
    logrus.Info("hello: inside helloWorld")

    bodyBuffer, err := ioutil.ReadAll(r.Body)
    if err != nil {
        logrus.Info("error while reading:" + err.Error())
        w.Write([]byte("GO: error in reading request body"))
    } else {
        logrus.Info("body : " + string(bodyBuffer))

        w.Write([]byte("GO: return hello"))
    }
}
```

After deployment, I invoke a POST api request with following JSON body:
```
{ 
    "a": "b"
}
```
Logs from Application Insight:
<img width="1316" alt="logs" src="https://user-images.githubusercontent.com/1285976/89127547-12e55a80-d4a3-11ea-9436-0a682c324778.png">

function.json
```
{
    "bindings": [
        {
            "authLevel": "anonymous",
            "type": "httpTrigger",
            "direction": "in",
            "name": "req",
            "methods": ["get", "post"]
        },
        {
            "type": "http",
            "direction": "out",
            "name": "res"
        }
    ]
}
```

I tried to enable "FUNCTIONS_V2_COMPATIBILITY_MODE" but that did not help either.

My code is hosted here: https://github.com/mpurusottamc/azurefunc-go

Any suggestions on how to debug this?

**Comment by jnsgruk** [comment]
I'm also suffering with this issue - note that it only started happening late last week - before that it was working fine.

I've also tried using the FUNCTIONS_V2_COMPATIBILITY_MODE, changing to not sending the "Content-Type" header, and MITM'd the outbound request to check that the client is sending a correctly formed request - and it all seems fine

**Comment by brettsam** [comment]
@mhoeger / @pragnagopa -- did something change here that can affect language workers? I know the perf changes had some impact here...

**Comment by mpurusottamc** [comment]
It seems to be a Windows OS related issue for Function Apps. When i updated the OS type to Linux, i do receive the request payload.

Here's my functionapp creation command:
```
az functionapp create --resource-group hellogogrplinux --os-type Linux --consumption-plan-location eastus --runtime node --runtime-version 10 --functions-version 3 --name hellogoapplinux --storage-account hellogostglinux
```

Here's my updated log:
```
time="2020-08-06T03:21:38Z" level=info msg="body : {\n \"a\": \"b\"\n}"
```

**Comment by jnsgruk** [comment]
Interesting. Is it possible to use the custom handler with a Linux host? I was under the impression that was limited to Windows hosts? 

My current app works by uploaded a cross-compiled exe file built using the cross-compile functionality in the Go compiler.

**Comment by pragnagopa** [comment]
@mpurusottamc - Thanks for reporting the issue. This is a known issue which is fixed recently - https://github.com/Azure/azure-functions-host/issues/6305 . Fix is rolling out production this week as part of runtime version: 3.0.14251 . I will close this issue for now. Please reactivate if you still see this issue on latest runtime. 

@jnsgruk - Custom handlers are supported on linux consumption with pre-built binaries for amd64

**Comment by jnsgruk** [comment]
@pragnagopa I'm pretty sure this is still an issue - I've not been able to resolve... when does "3.0.14251" go live??

**Comment by pragnagopa** [comment]
Please watch https://github.com/Azure/app-service-announcements/issues/275 for release updates. ETA for complete roll out 1 week from now.
